import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { PageFrame } from "../components/cinematic/PageFrame";
import { CHARACTERS, characterById } from "../data/characters";
import { useArchiveMode } from "../context/ArchiveModeContext";

export function Character() {
  const { id } = useParams<{ id: string }>();
  const character = characterById(id);
  const { mode, setMode } = useArchiveMode();
  const [revealed, setRevealed] = useState(false);
  if (!character) return <PageFrame eyebrow="404" title="Ficha não encontrada"><p className="text-mist">Este nome não consta no elenco.</p><Link className="mt-6 inline-block font-mono text-xs uppercase tracking-ultra text-signal" to="/personagens">Voltar ao elenco</Link></PageFrame>;
  const index = CHARACTERS.findIndex((entry) => entry.id === character.id);
  const previous = index > 0 ? CHARACTERS[index - 1] : undefined;
  const next = index < CHARACTERS.length - 1 ? CHARACTERS[index + 1] : undefined;
  return <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1 }}><PageFrame eyebrow={`Ficha · ${character.roleLabel}`} title={character.fullName} subtitle={character.summary}>
    <div className="mt-8 space-y-10">
      <Link to="/personagens" className="inline-flex rounded border border-stroke px-3 py-2 font-mono text-[10px] uppercase tracking-ultra text-mist hover:border-signal/50 hover:text-bone">← Voltar ao elenco</Link>
      <section className="grid gap-8 rounded-xl border border-stroke bg-panel/60 p-5 sm:grid-cols-[12rem_minmax(0,1fr)] sm:p-8"><div><img src={character.profilePic} alt={`Retrato de ${character.fullName}`} className="aspect-square w-full rounded-xl border border-signal/25 object-cover" /></div><div><p className="font-mono text-[10px] uppercase tracking-ultra text-signal/80">{character.occupation} · {character.age} anos</p><p className="mt-4 font-display text-2xl italic text-bone/90">“{character.quote}”</p><p className="mt-5 text-sm leading-relaxed text-mist">{character.personality}</p><div className="mt-5 flex flex-wrap gap-2">{character.locations.map((location) => <Link key={location} to={`/locais/${location}`} className="rounded-full border border-stroke px-3 py-1.5 font-mono text-[10px] text-mist hover:border-signal/50 hover:text-bone">{location.split("-").join(" ")}</Link>)}</div></div></section>
      <div className="grid gap-8 lg:grid-cols-2"><section><h2 className="font-mono text-[10px] uppercase tracking-ultra text-signal/85">Aparência</h2><ul className="mt-4 space-y-2 text-sm text-mist">{character.appearance.map((item) => <li key={item} className="border-l border-stroke pl-3">{item}</li>)}</ul><h2 className="mt-8 font-mono text-[10px] uppercase tracking-ultra text-signal/85">História</h2><p className="mt-4 text-base leading-relaxed text-mist">{character.history}</p></section><section><h2 className="font-mono text-[10px] uppercase tracking-ultra text-signal/85">Atributos</h2><div className="mt-4 grid grid-cols-4 gap-2">{Object.entries({ PV: character.hitPoints, PE: character.effortPoints, For: character.attributes.str, Res: character.attributes.con, Agi: character.attributes.dex, Sab: character.attributes.knw, Int: character.attributes.int, Cha: character.attributes.char }).map(([label, value]) => <div key={label} className="rounded border border-stroke bg-panel p-3 text-center"><span className="block font-mono text-[9px] text-mist">{label}</span><span className="mt-1 block text-bone">{value}</span></div>)}</div><h2 className="mt-8 font-mono text-[10px] uppercase tracking-ultra text-signal/85">Perícias</h2><ul className="mt-4 grid gap-2 text-sm text-mist sm:grid-cols-2">{character.skills.map((skill) => <li key={skill} className="rounded border border-stroke p-2">{skill}</li>)}</ul></section></div>
      <section className="rounded-xl border border-stroke bg-panel/60 p-5">
        <div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-mono text-[10px] uppercase tracking-ultra text-signal/85">Informações de mesa</h2><p className="mt-2 text-sm text-mist">O modo Jogador é padrão. Pistas e segredos são revelados explicitamente no modo Mestre.</p></div><div className="inline-flex rounded border border-stroke p-1" role="group" aria-label="Modo de leitura"><button type="button" aria-pressed={mode === "jogador"} onClick={() => { setMode("jogador"); setRevealed(false); }} className={`rounded px-3 py-2 font-mono text-[10px] uppercase tracking-ultra ${mode === "jogador" ? "bg-bone/10 text-bone" : "text-mist"}`}>Jogador</button><button type="button" aria-pressed={mode === "mestre"} onClick={() => { setMode("mestre"); setRevealed(false); }} className={`rounded px-3 py-2 font-mono text-[10px] uppercase tracking-ultra ${mode === "mestre" ? "bg-signal/15 text-signal" : "text-mist"}`}>Mestre</button></div></div>
        <div className="mt-5 border-t border-stroke pt-5">{mode === "jogador" ? <p className="text-sm text-mist/70">Arquivo público ativo. Pistas e conteúdo confidencial ocultos.</p> : revealed ? <div className="grid gap-6 sm:grid-cols-2"><div><h3 className="font-mono text-[10px] uppercase tracking-ultra text-signal/80">Objetivos</h3><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-mist">{character.objectives.map((item) => <li key={item}>{item}</li>)}</ul><h3 className="mt-5 font-mono text-[10px] uppercase tracking-ultra text-signal/80">Relações</h3><ul className="mt-3 space-y-2 text-sm text-mist">{character.relations.map((relation) => <li key={relation.characterId}><Link to={`/personagens/${relation.characterId}`} className="text-bone hover:text-signal">{relation.label}</Link> — {relation.detail}</li>)}</ul></div><div><h3 className="font-mono text-[10px] uppercase tracking-ultra text-signal/80">Pistas</h3><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-mist">{character.clues.map((item) => <li key={item}>{item}</li>)}</ul><h3 className="mt-5 font-mono text-[10px] uppercase tracking-ultra text-signal">Segredos</h3><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-bone/90">{character.secrets.map((item) => <li key={item}>{item}</li>)}</ul></div></div> : <div role="alert"><p className="text-sm text-mist">Aviso: esta ficha contém pistas e spoilers da campanha.</p><button type="button" onClick={() => setRevealed(true)} className="mt-3 rounded border border-signal/50 px-3 py-2 font-mono text-[10px] uppercase tracking-ultra text-signal">Revelar informações do mestre</button></div>}</div>
      </section>
      <nav className="grid gap-3 border-t border-stroke pt-6 sm:grid-cols-2" aria-label="Navegação entre fichas">{previous ? <Link to={`/personagens/${previous.id}`} className="rounded border border-stroke p-4 hover:border-signal/50"><span className="block font-mono text-[9px] uppercase tracking-ultra text-mist">← Anterior</span><span className="mt-2 block text-bone">{previous.fullName}</span></Link> : <span />}{next ? <Link to={`/personagens/${next.id}`} className="rounded border border-stroke p-4 text-right hover:border-signal/50"><span className="block font-mono text-[9px] uppercase tracking-ultra text-mist">Próximo →</span><span className="mt-2 block text-bone">{next.fullName}</span></Link> : null}</nav>
    </div>
  </PageFrame></motion.div>;
}
